# Generated by Codex on 2026-05-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0025_application_workflow_statuses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("applied", "Applied"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("mcq_completed", "MCQ Completed"),
                    ("hired", "Hired"),
                    ("pending", "Pending"),
                    ("under_review", "Under Review"),
                    ("interview_completed", "Interview Completed"),
                ],
                default="applied",
                max_length=20,
            ),
        ),
    ]
